# Toggle debug mode, used for development of Nexeres.
# Although, you can set this true while developing your own application,
# it is not recommended to use this in production.
# A non-exhaustive list of the effects of debug mode:
# - CSRF is disabled.
# - CORS is configured differently.
# - Debug logs are enabled. (Noisy output)
debug: true

# List of admin users for Nexeres.
admins:
  - email: admin@example.com
    # Bcrypt password hash only
    passwordHash: $2a$10$eImiTMZG4Tn0y1N9O8e5uO3b6z5Z5j7f5Z5j7f5Z5j7f5Z5j7f5Z5j7

# Configure the multitenancy feature.
# This feature is not enabled by default.
# When enabled, it allows Nexeres to handle multiple tenants.
# Each tenant can have its own configuration, users, and settings.
# Note: This feature is experimental and may not be fully stable.
multitenancy:
  # Enable or disable multitenancy.
  enabled: false

# Configure notifications for Nexeres.
# Currently, only email notifications are supported.
notifications:
  # Configure email notifications.
  email:
    # The directory holding any custom email templates.
    # If provided, it should have ALL the required templates.
    # The default templates are used if this is not provided.
    # templatesDir: /path/to/custom/templates

    # The provider for email notifications. One of smtp, ses, or sendgrid.
    provider: smtp
