version: "3"

dotenv: [".env.local", ".env"]

env:
  DEV_DATA_DIR: "./data/nexeres-data"

tasks:
  setup-pgadmin:
    desc: Setup pgAdmin for managing the PostgreSQL database
    cmds:
      - echo "Setting up pgAdmin..."
      - sudo chown -R 5050:5050 ./data/nexeres-pgadmin-data
      - echo "pgAdmin setup complete. Permissions set to 5050:5050. for ./data/nexeres-pgadmin-data"

  oapi-spec-gen:
    desc: Generate the OpenAPI specification from the Go code
    cmd: swag init -o oapispec

  db-gen:
    desc: Generate the database objects, querriers, etc.
    cmd: sqlc generate

  db-migrate-up-all:
    desc: run the database migrations
    dir: sqlc/migrations
    cmd: migrate -source file://$(pwd) -database "postgres://$NEXERES_DB_USER:$NEXERES_DB_PASSWORD@$NEXERES_DB_HOST:$NEXERES_DB_PORT/$NEXERES_DB_NAME?sslmode=disable" up

  db-migrate-down-all:
    desc: rollback all the database migrations
    dir: sqlc/migrations
    cmd: migrate -source file://$(pwd) -database "postgres://$NEXERES_DB_USER:$NEXERES_DB_PASSWORD@$NEXERES_DB_HOST:$NEXERES_DB_PORT/$NEXERES_DB_NAME?sslmode=disable" down

  dev:
    desc: Run the development server
    cmds:
      - docker compose up -d
      - sleep 5
      - CompileDaemon -exclude-dir .git -exclude-dir run-logs -exclude-dir public -exclude-dir run -exclude-dir data -include config.nbrglm.yaml -include *.html -include *.css -build "go build -o build/debug/backend" -command "./build/debug/backend serve --config config.nbrglm.yaml"

  rebuild-db-dev:
    desc: Rebuild the database
    cmds:
      - echo "Rebuilding the database..."
      - echo "Stopping and removing existing containers..."
      - docker compose down
      - echo "Removing existing data directory..."
      - sudo rm -rf ${DEV_DATA_DIR}
      - echo "Creating new data directory..."
      - mkdir -p ${DEV_DATA_DIR}
      - echo "Starting the database containers..."
      - docker compose up -d
      - echo "Waiting for the database to start..."
      - sleep 20
      - echo "Running migrations..."
      - task db-migrate-up-all
      - echo "Database rebuild complete."
