/*
NBRGLM Auth Platform

This is the NBRGLM Auth Platform API documentation.

API version: 0.0.1
Contact: contact@nbrglm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth_platform_go_sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the HandlersSendVerificationEmailData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlersSendVerificationEmailData{}

// HandlersSendVerificationEmailData struct for HandlersSendVerificationEmailData
type HandlersSendVerificationEmailData struct {
	Email string `json:"email"`
	AdditionalProperties map[string]interface{}
}

type _HandlersSendVerificationEmailData HandlersSendVerificationEmailData

// NewHandlersSendVerificationEmailData instantiates a new HandlersSendVerificationEmailData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlersSendVerificationEmailData(email string) *HandlersSendVerificationEmailData {
	this := HandlersSendVerificationEmailData{}
	this.Email = email
	return &this
}

// NewHandlersSendVerificationEmailDataWithDefaults instantiates a new HandlersSendVerificationEmailData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlersSendVerificationEmailDataWithDefaults() *HandlersSendVerificationEmailData {
	this := HandlersSendVerificationEmailData{}
	return &this
}

// GetEmail returns the Email field value
func (o *HandlersSendVerificationEmailData) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *HandlersSendVerificationEmailData) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *HandlersSendVerificationEmailData) SetEmail(v string) {
	o.Email = v
}

func (o HandlersSendVerificationEmailData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlersSendVerificationEmailData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HandlersSendVerificationEmailData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandlersSendVerificationEmailData := _HandlersSendVerificationEmailData{}

	err = json.Unmarshal(data, &varHandlersSendVerificationEmailData)

	if err != nil {
		return err
	}

	*o = HandlersSendVerificationEmailData(varHandlersSendVerificationEmailData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "email")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHandlersSendVerificationEmailData struct {
	value *HandlersSendVerificationEmailData
	isSet bool
}

func (v NullableHandlersSendVerificationEmailData) Get() *HandlersSendVerificationEmailData {
	return v.value
}

func (v *NullableHandlersSendVerificationEmailData) Set(val *HandlersSendVerificationEmailData) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlersSendVerificationEmailData) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlersSendVerificationEmailData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlersSendVerificationEmailData(val *HandlersSendVerificationEmailData) *NullableHandlersSendVerificationEmailData {
	return &NullableHandlersSendVerificationEmailData{value: val, isSet: true}
}

func (v NullableHandlersSendVerificationEmailData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlersSendVerificationEmailData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


