/*
NBRGLM Auth Platform

This is the NBRGLM Auth Platform API documentation.

API version: 0.0.1
Contact: contact@nbrglm.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth_platform_go_sdk

import (
	"encoding/json"
)

// checks if the ModelsErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsErrorResponse{}

// ModelsErrorResponse struct for ModelsErrorResponse
type ModelsErrorResponse struct {
	// Code is an error code that can be used for programmatic handling of errors.
	Code *int32 `json:"code,omitempty"`
	// DebugMessage is a technical message that can be used for debugging.
	Debug *string `json:"debug,omitempty"`
	// Message is a user-friendly message that can be displayed to the end user.
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelsErrorResponse ModelsErrorResponse

// NewModelsErrorResponse instantiates a new ModelsErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsErrorResponse() *ModelsErrorResponse {
	this := ModelsErrorResponse{}
	return &this
}

// NewModelsErrorResponseWithDefaults instantiates a new ModelsErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsErrorResponseWithDefaults() *ModelsErrorResponse {
	this := ModelsErrorResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ModelsErrorResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsErrorResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ModelsErrorResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ModelsErrorResponse) SetCode(v int32) {
	o.Code = &v
}

// GetDebug returns the Debug field value if set, zero value otherwise.
func (o *ModelsErrorResponse) GetDebug() string {
	if o == nil || IsNil(o.Debug) {
		var ret string
		return ret
	}
	return *o.Debug
}

// GetDebugOk returns a tuple with the Debug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsErrorResponse) GetDebugOk() (*string, bool) {
	if o == nil || IsNil(o.Debug) {
		return nil, false
	}
	return o.Debug, true
}

// HasDebug returns a boolean if a field has been set.
func (o *ModelsErrorResponse) HasDebug() bool {
	if o != nil && !IsNil(o.Debug) {
		return true
	}

	return false
}

// SetDebug gets a reference to the given string and assigns it to the Debug field.
func (o *ModelsErrorResponse) SetDebug(v string) {
	o.Debug = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ModelsErrorResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ModelsErrorResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ModelsErrorResponse) SetMessage(v string) {
	o.Message = &v
}

func (o ModelsErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Debug) {
		toSerialize["debug"] = o.Debug
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelsErrorResponse) UnmarshalJSON(data []byte) (err error) {
	varModelsErrorResponse := _ModelsErrorResponse{}

	err = json.Unmarshal(data, &varModelsErrorResponse)

	if err != nil {
		return err
	}

	*o = ModelsErrorResponse(varModelsErrorResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "debug")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelsErrorResponse struct {
	value *ModelsErrorResponse
	isSet bool
}

func (v NullableModelsErrorResponse) Get() *ModelsErrorResponse {
	return v.value
}

func (v *NullableModelsErrorResponse) Set(val *ModelsErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsErrorResponse(val *ModelsErrorResponse) *NullableModelsErrorResponse {
	return &NullableModelsErrorResponse{value: val, isSet: true}
}

func (v NullableModelsErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


