# coding: utf-8

# flake8: noqa
"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from auth_platform_py_sdk.models.handlers_logout_result import HandlersLogoutResult
    from auth_platform_py_sdk.models.handlers_refresh_token_result import HandlersRefreshTokenResult
    from auth_platform_py_sdk.models.handlers_send_verification_email_data import HandlersSendVerificationEmailData
    from auth_platform_py_sdk.models.handlers_send_verification_email_result import HandlersSendVerificationEmailResult
    from auth_platform_py_sdk.models.handlers_user_flow_data import HandlersUserFlowData
    from auth_platform_py_sdk.models.handlers_user_login_data import HandlersUserLoginData
    from auth_platform_py_sdk.models.handlers_user_login_result import HandlersUserLoginResult
    from auth_platform_py_sdk.models.handlers_user_signup_data import HandlersUserSignupData
    from auth_platform_py_sdk.models.handlers_user_signup_result import HandlersUserSignupResult
    from auth_platform_py_sdk.models.handlers_verify_email_token_data import HandlersVerifyEmailTokenData
    from auth_platform_py_sdk.models.handlers_verify_email_token_result import HandlersVerifyEmailTokenResult
    from auth_platform_py_sdk.models.models_error_response import ModelsErrorResponse
    from auth_platform_py_sdk.models.models_org_compat import ModelsOrgCompat
    from auth_platform_py_sdk.models.tokens_tokens import TokensTokens
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from auth_platform_py_sdk.models.handlers_logout_result import HandlersLogoutResult
from auth_platform_py_sdk.models.handlers_refresh_token_result import HandlersRefreshTokenResult
from auth_platform_py_sdk.models.handlers_send_verification_email_data import HandlersSendVerificationEmailData
from auth_platform_py_sdk.models.handlers_send_verification_email_result import HandlersSendVerificationEmailResult
from auth_platform_py_sdk.models.handlers_user_flow_data import HandlersUserFlowData
from auth_platform_py_sdk.models.handlers_user_login_data import HandlersUserLoginData
from auth_platform_py_sdk.models.handlers_user_login_result import HandlersUserLoginResult
from auth_platform_py_sdk.models.handlers_user_signup_data import HandlersUserSignupData
from auth_platform_py_sdk.models.handlers_user_signup_result import HandlersUserSignupResult
from auth_platform_py_sdk.models.handlers_verify_email_token_data import HandlersVerifyEmailTokenData
from auth_platform_py_sdk.models.handlers_verify_email_token_result import HandlersVerifyEmailTokenResult
from auth_platform_py_sdk.models.models_error_response import ModelsErrorResponse
from auth_platform_py_sdk.models.models_org_compat import ModelsOrgCompat
from auth_platform_py_sdk.models.tokens_tokens import TokensTokens

""",
            name=__name__,
            doc=__doc__,
        )
    )
