# coding: utf-8

# flake8: noqa

"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.1"

# Define package exports
__all__ = [
    "AuthApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HandlersLogoutResult",
    "HandlersRefreshTokenResult",
    "HandlersSendVerificationEmailData",
    "HandlersSendVerificationEmailResult",
    "HandlersUserFlowData",
    "HandlersUserLoginData",
    "HandlersUserLoginResult",
    "HandlersUserSignupData",
    "HandlersUserSignupResult",
    "HandlersVerifyEmailTokenData",
    "HandlersVerifyEmailTokenResult",
    "ModelsErrorResponse",
    "ModelsOrgCompat",
    "TokensTokens",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from auth_platform_py_sdk.api.auth_api import AuthApi as AuthApi
    
    # import ApiClient
    from auth_platform_py_sdk.api_response import ApiResponse as ApiResponse
    from auth_platform_py_sdk.api_client import ApiClient as ApiClient
    from auth_platform_py_sdk.configuration import Configuration as Configuration
    from auth_platform_py_sdk.exceptions import OpenApiException as OpenApiException
    from auth_platform_py_sdk.exceptions import ApiTypeError as ApiTypeError
    from auth_platform_py_sdk.exceptions import ApiValueError as ApiValueError
    from auth_platform_py_sdk.exceptions import ApiKeyError as ApiKeyError
    from auth_platform_py_sdk.exceptions import ApiAttributeError as ApiAttributeError
    from auth_platform_py_sdk.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from auth_platform_py_sdk.models.handlers_logout_result import HandlersLogoutResult as HandlersLogoutResult
    from auth_platform_py_sdk.models.handlers_refresh_token_result import HandlersRefreshTokenResult as HandlersRefreshTokenResult
    from auth_platform_py_sdk.models.handlers_send_verification_email_data import HandlersSendVerificationEmailData as HandlersSendVerificationEmailData
    from auth_platform_py_sdk.models.handlers_send_verification_email_result import HandlersSendVerificationEmailResult as HandlersSendVerificationEmailResult
    from auth_platform_py_sdk.models.handlers_user_flow_data import HandlersUserFlowData as HandlersUserFlowData
    from auth_platform_py_sdk.models.handlers_user_login_data import HandlersUserLoginData as HandlersUserLoginData
    from auth_platform_py_sdk.models.handlers_user_login_result import HandlersUserLoginResult as HandlersUserLoginResult
    from auth_platform_py_sdk.models.handlers_user_signup_data import HandlersUserSignupData as HandlersUserSignupData
    from auth_platform_py_sdk.models.handlers_user_signup_result import HandlersUserSignupResult as HandlersUserSignupResult
    from auth_platform_py_sdk.models.handlers_verify_email_token_data import HandlersVerifyEmailTokenData as HandlersVerifyEmailTokenData
    from auth_platform_py_sdk.models.handlers_verify_email_token_result import HandlersVerifyEmailTokenResult as HandlersVerifyEmailTokenResult
    from auth_platform_py_sdk.models.models_error_response import ModelsErrorResponse as ModelsErrorResponse
    from auth_platform_py_sdk.models.models_org_compat import ModelsOrgCompat as ModelsOrgCompat
    from auth_platform_py_sdk.models.tokens_tokens import TokensTokens as TokensTokens
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from auth_platform_py_sdk.api.auth_api import AuthApi as AuthApi

# import ApiClient
from auth_platform_py_sdk.api_response import ApiResponse as ApiResponse
from auth_platform_py_sdk.api_client import ApiClient as ApiClient
from auth_platform_py_sdk.configuration import Configuration as Configuration
from auth_platform_py_sdk.exceptions import OpenApiException as OpenApiException
from auth_platform_py_sdk.exceptions import ApiTypeError as ApiTypeError
from auth_platform_py_sdk.exceptions import ApiValueError as ApiValueError
from auth_platform_py_sdk.exceptions import ApiKeyError as ApiKeyError
from auth_platform_py_sdk.exceptions import ApiAttributeError as ApiAttributeError
from auth_platform_py_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from auth_platform_py_sdk.models.handlers_logout_result import HandlersLogoutResult as HandlersLogoutResult
from auth_platform_py_sdk.models.handlers_refresh_token_result import HandlersRefreshTokenResult as HandlersRefreshTokenResult
from auth_platform_py_sdk.models.handlers_send_verification_email_data import HandlersSendVerificationEmailData as HandlersSendVerificationEmailData
from auth_platform_py_sdk.models.handlers_send_verification_email_result import HandlersSendVerificationEmailResult as HandlersSendVerificationEmailResult
from auth_platform_py_sdk.models.handlers_user_flow_data import HandlersUserFlowData as HandlersUserFlowData
from auth_platform_py_sdk.models.handlers_user_login_data import HandlersUserLoginData as HandlersUserLoginData
from auth_platform_py_sdk.models.handlers_user_login_result import HandlersUserLoginResult as HandlersUserLoginResult
from auth_platform_py_sdk.models.handlers_user_signup_data import HandlersUserSignupData as HandlersUserSignupData
from auth_platform_py_sdk.models.handlers_user_signup_result import HandlersUserSignupResult as HandlersUserSignupResult
from auth_platform_py_sdk.models.handlers_verify_email_token_data import HandlersVerifyEmailTokenData as HandlersVerifyEmailTokenData
from auth_platform_py_sdk.models.handlers_verify_email_token_result import HandlersVerifyEmailTokenResult as HandlersVerifyEmailTokenResult
from auth_platform_py_sdk.models.models_error_response import ModelsErrorResponse as ModelsErrorResponse
from auth_platform_py_sdk.models.models_org_compat import ModelsOrgCompat as ModelsOrgCompat
from auth_platform_py_sdk.models.tokens_tokens import TokensTokens as TokensTokens

""",
            name=__name__,
            doc=__doc__,
        )
    )
