# coding: utf-8

"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from auth_platform_py_sdk.models.handlers_user_flow_data import HandlersUserFlowData

class TestHandlersUserFlowData(unittest.TestCase):
    """HandlersUserFlowData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersUserFlowData:
        """Test HandlersUserFlowData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersUserFlowData`
        """
        model = HandlersUserFlowData()
        if include_optional:
            return HandlersUserFlowData(
                created_at = '',
                email = '',
                expires_at = '',
                id = '',
                invite_token = '',
                mfa_required = True,
                mfa_verified = True,
                orgs = [
                    auth_platform_py_sdk.models.models/org_compat.models.OrgCompat(
                        avatar_url = '', 
                        created_at = '', 
                        deleted_at = '', 
                        description = '', 
                        id = '', 
                        name = '', 
                        settings = {
                            'key' : None
                            }, 
                        slug = '', 
                        updated_at = '', )
                    ],
                return_to = '',
                sso_provider = '',
                sso_user_id = '',
                type = '',
                user_id = ''
            )
        else:
            return HandlersUserFlowData(
        )
        """

    def testHandlersUserFlowData(self):
        """Test HandlersUserFlowData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
