# coding: utf-8

"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from auth_platform_py_sdk.models.handlers_verify_email_token_data import HandlersVerifyEmailTokenData

class TestHandlersVerifyEmailTokenData(unittest.TestCase):
    """HandlersVerifyEmailTokenData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersVerifyEmailTokenData:
        """Test HandlersVerifyEmailTokenData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersVerifyEmailTokenData`
        """
        model = HandlersVerifyEmailTokenData()
        if include_optional:
            return HandlersVerifyEmailTokenData(
                token = ''
            )
        else:
            return HandlersVerifyEmailTokenData(
                token = '',
        )
        """

    def testHandlersVerifyEmailTokenData(self):
        """Test HandlersVerifyEmailTokenData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
