# coding: utf-8

"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from auth_platform_py_sdk.models.handlers_user_login_data import HandlersUserLoginData

class TestHandlersUserLoginData(unittest.TestCase):
    """HandlersUserLoginData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersUserLoginData:
        """Test HandlersUserLoginData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersUserLoginData`
        """
        model = HandlersUserLoginData()
        if include_optional:
            return HandlersUserLoginData(
                email = '',
                flow_return_to = '',
                password = ''
            )
        else:
            return HandlersUserLoginData(
                email = '',
                password = '',
        )
        """

    def testHandlersUserLoginData(self):
        """Test HandlersUserLoginData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
