# coding: utf-8

"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from auth_platform_py_sdk.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_api_auth_flow_flow_id_get(self) -> None:
        """Test case for api_auth_flow_flow_id_get

        Get User Flow Data
        """
        pass

    def test_api_auth_login_post(self) -> None:
        """Test case for api_auth_login_post

        User Login
        """
        pass

    def test_api_auth_logout_post(self) -> None:
        """Test case for api_auth_logout_post

        Logout user
        """
        pass

    def test_api_auth_refresh_post(self) -> None:
        """Test case for api_auth_refresh_post

        Refresh Token
        """
        pass

    def test_api_auth_signup_post(self) -> None:
        """Test case for api_auth_signup_post

        User Signup
        """
        pass

    def test_api_auth_verify_email_send_post(self) -> None:
        """Test case for api_auth_verify_email_send_post

        Send Verification Email
        """
        pass

    def test_api_auth_verify_email_verify_post(self) -> None:
        """Test case for api_auth_verify_email_verify_post

        Verify Email Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
