# coding: utf-8

"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from auth_platform_py_sdk.models.tokens_tokens import TokensTokens

class TestTokensTokens(unittest.TestCase):
    """TokensTokens unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokensTokens:
        """Test TokensTokens
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokensTokens`
        """
        model = TokensTokens()
        if include_optional:
            return TokensTokens(
                refresh_token = '',
                refresh_token_expiry = '',
                session_id = '',
                session_token = '',
                session_token_expiry = ''
            )
        else:
            return TokensTokens(
        )
        """

    def testTokensTokens(self):
        """Test TokensTokens"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
