# coding: utf-8

"""
    NBRGLM Auth Platform

    This is the NBRGLM Auth Platform API documentation.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@nbrglm.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from auth_platform_py_sdk.models.handlers_send_verification_email_data import HandlersSendVerificationEmailData

class TestHandlersSendVerificationEmailData(unittest.TestCase):
    """HandlersSendVerificationEmailData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersSendVerificationEmailData:
        """Test HandlersSendVerificationEmailData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersSendVerificationEmailData`
        """
        model = HandlersSendVerificationEmailData()
        if include_optional:
            return HandlersSendVerificationEmailData(
                email = ''
            )
        else:
            return HandlersSendVerificationEmailData(
                email = '',
        )
        """

    def testHandlersSendVerificationEmailData(self):
        """Test HandlersSendVerificationEmailData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
