/**
 * NBRGLM Auth Platform
 * This is the NBRGLM Auth Platform API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@nbrglm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class HandlersUserSignupData {
    'confirmPassword': string;
    'email': string;
    'firstName': string;
    /**
    * Optional invite token for signup
    */
    'inviteToken'?: string;
    'lastName': string;
    'password': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "confirmPassword",
            "baseName": "confirmPassword",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "inviteToken",
            "baseName": "inviteToken",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HandlersUserSignupData.attributeTypeMap;
    }
}

