/**
 * NBRGLM Auth Platform
 * This is the NBRGLM Auth Platform API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@nbrglm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class HandlersUserLoginData {
    'email': string;
    /**
    * Optional field to store in the flow data which can be fetched by the client after login This can be used to redirect the user to a specific page after login or to maintain the state of the application. It is recommended to validate this field on the client side to prevent open redirect vulnerabilities.
    */
    'flowReturnTo'?: string;
    'password': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "flowReturnTo",
            "baseName": "flowReturnTo",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HandlersUserLoginData.attributeTypeMap;
    }
}

