/**
 * NBRGLM Auth Platform
 * This is the NBRGLM Auth Platform API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@nbrglm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TokensTokens } from './tokensTokens';

export class HandlersUserLoginResult {
    'flowId'?: string;
    'message'?: string;
    'requireEmailVerification'?: boolean;
    'tokens'?: TokensTokens;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flowId",
            "baseName": "flowId",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requireEmailVerification",
            "baseName": "requireEmailVerification",
            "type": "boolean"
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "TokensTokens"
        }    ];

    static getAttributeTypeMap() {
        return HandlersUserLoginResult.attributeTypeMap;
    }
}

