/**
 * NBRGLM Auth Platform
 * This is the NBRGLM Auth Platform API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@nbrglm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelsOrgCompat } from './modelsOrgCompat';

export class HandlersUserFlowData {
    'createdAt'?: string;
    'email'?: string;
    'expiresAt'?: string;
    'id'?: string;
    /**
    * For Invite Flow
    */
    'inviteToken'?: string;
    'mfaRequired'?: boolean;
    'mfaVerified'?: boolean;
    'orgs'?: Array<ModelsOrgCompat>;
    /**
    * URL to redirect after flow completion
    */
    'returnTo'?: string;
    /**
    * For SSO Flow, e.g., \"google\", \"github\", etc.
    */
    'ssoProvider'?: string;
    /**
    * For SSO Flow, External User ID
    */
    'ssoUserId'?: string;
    'type'?: string;
    'userId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inviteToken",
            "baseName": "inviteToken",
            "type": "string"
        },
        {
            "name": "mfaRequired",
            "baseName": "mfaRequired",
            "type": "boolean"
        },
        {
            "name": "mfaVerified",
            "baseName": "mfaVerified",
            "type": "boolean"
        },
        {
            "name": "orgs",
            "baseName": "orgs",
            "type": "Array<ModelsOrgCompat>"
        },
        {
            "name": "returnTo",
            "baseName": "returnTo",
            "type": "string"
        },
        {
            "name": "ssoProvider",
            "baseName": "ssoProvider",
            "type": "string"
        },
        {
            "name": "ssoUserId",
            "baseName": "ssoUserId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HandlersUserFlowData.attributeTypeMap;
    }
}

