/**
 * NBRGLM Auth Platform
 * This is the NBRGLM Auth Platform API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@nbrglm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelsOrgCompat {
    'avatarURL'?: string;
    'createdAt'?: string;
    'deletedAt'?: string;
    'description'?: string;
    'id'?: string;
    'name'?: string;
    'settings'?: { [key: string]: object; };
    'slug'?: string;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatarURL",
            "baseName": "avatarURL",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string"
        },
        {
            "name": "deletedAt",
            "baseName": "deletedAt",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ModelsOrgCompat.attributeTypeMap;
    }
}

