/**
 * NBRGLM Auth Platform
 * This is the NBRGLM Auth Platform API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@nbrglm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelsErrorResponse {
    /**
    * Code is an error code that can be used for programmatic handling of errors.
    */
    'code'?: number;
    /**
    * DebugMessage is a technical message that can be used for debugging.
    */
    'debug'?: string;
    /**
    * Message is a user-friendly message that can be displayed to the end user.
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "debug",
            "baseName": "debug",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ModelsErrorResponse.attributeTypeMap;
    }
}

