/**
 * NBRGLM Auth Platform
 * This is the NBRGLM Auth Platform API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@nbrglm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TokensTokens {
    /**
    * RefreshToken is the generated refresh token.  This is base64.RawURLEncoding encoded. DO NOT DECODE IT WHILE RETRIEVING IT FROM THE COOKIES/CLIENT.
    */
    'refreshToken'?: string;
    /**
    * RefreshTokenExpiry is the expiration time of the refresh token.
    */
    'refreshTokenExpiry'?: string;
    /**
    * SessionId is the unique identifier for the session.
    */
    'sessionId'?: string;
    /**
    * SessionToken is the generated session token.  This is a jwt which is base64.RawURLEncoding encoded. YOU NEED TO DECODE IT WHILE RETRIEVING IT FROM THE COOKIES/CLIENT. DO NOT USE IT AS IS. VALIDATION WILL FAIL WITHOUT DECODING. ONLY WHEN DECODED, YOU SHOULD PASS IT TO THE THINGS THAT REQUIRE THE SESSION TOKEN.
    */
    'sessionToken'?: string;
    /**
    * SessionTokenExpiry is the expiration time of the session token.
    */
    'sessionTokenExpiry'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "refreshToken",
            "baseName": "refresh_token",
            "type": "string"
        },
        {
            "name": "refreshTokenExpiry",
            "baseName": "refresh_token_expiry",
            "type": "string"
        },
        {
            "name": "sessionId",
            "baseName": "session_id",
            "type": "string"
        },
        {
            "name": "sessionToken",
            "baseName": "session_token",
            "type": "string"
        },
        {
            "name": "sessionTokenExpiry",
            "baseName": "session_token_expiry",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TokensTokens.attributeTypeMap;
    }
}

