name: Release SDKs

on:
  push:
    tags:
      - 'v*'
env:
  SDKS_DIR: "sdks"
  GO_CLIENT_DIR: "sdks/auth_platform_go_sdk"
  NODE_CLIENT_DIR: "sdks/auth_platform_node_sdk"
  PYTHON_CLIENT_DIR: "sdks/auth_platform_py_sdk"
  SPEC_FILE: "sdks/swagger.yaml"
  GO_GEN_SDK_DIR: ./go-client
  NODE_GEN_SDK_DIR: ./typescript-node-client
  PYTHON_GEN_SDK_DIR: ./python-client


jobs:
  generate-and-push-sdks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Get Version tags
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Clean up old SDKs
        run: rm -rf $SDKS_DIR && mkdir -p $GO_CLIENT_DIR $NODE_CLIENT_DIR $PYTHON_CLIENT_DIR
      
      - name: Generate OpenAPI Spec
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.4
          swag init -o $SDKS_DIR
          cp $SDKS_DIR/swagger.yaml swagger.yaml
          rm -rf $SDKS_DIR
          mv swagger.yaml $SPEC_FILE

      - name: Create Generator Config Golang
        run: |
          touch $SDKS_DIR/openapi-generator-config.go.yaml
          echo "packageName: auth_platform_go_sdk" >> $SDKS_DIR/openapi-generator-config.go.yaml
          echo "packageVersion: ${VERSION#v}" >> $SDKS_DIR/openapi-generator-config.go.yaml
          echo "disallowAdditionalPropertiesIfNotPresent: false" >> $SDKS_DIR/openapi-generator-config.go.yaml

      - name: Generate Go Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: go
          config-file: ${{env.SDKS_DIR}}/openapi-generator-config.go.yaml
          openapi-file: ${{env.SPEC_FILE}}

      - name: Move Go SDK
        run: |
          cp -r $GO_GEN_SDK_DIR/* $GO_CLIENT_DIR/
          rm -rf $GO_GEN_SDK_DIR

      - name: Create Generator Config NodeJS
        run: |
          touch $SDKS_DIR/openapi-generator-config.node.yaml
          echo "npmName: @nbrglm-devs/auth-platform-node-sdk" >> $SDKS_DIR/openapi-generator-config.node.yaml
          echo "npmVersion: ${VERSION#v}" >> $SDKS_DIR/openapi-generator-config.node.yaml
          echo "licenseName: Apache-2.0" >> $SDKS_DIR/openapi-generator-config.node.yaml
          echo "disallowAdditionalPropertiesIfNotPresent: false" >> $SDKS_DIR/openapi-generator-config.node.yaml

      - name: Generate Node Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: typescript-node
          config-file: ${{env.SDKS_DIR}}/openapi-generator-config.node.yaml
          openapi-file: ${{env.SPEC_FILE}}

      - name: Move Node SDK
        run: |
          cp -r $NODE_GEN_SDK_DIR/* $NODE_CLIENT_DIR/
          rm -rf $NODE_GEN_SDK_DIR

      - name: Create Generator Config Python
        run: |
          touch $SDKS_DIR/openapi-generator-config.python.yaml
          echo "packageName: auth_platform_py_sdk" >> $SDKS_DIR/openapi-generator-config.python.yaml
          echo "projectName: auth-platform-py-sdk" >> $SDKS_DIR/openapi-generator-config.python.yaml
          echo "packageUrl: https://github.com/nbrglm/auth-platform-py-sdk" >> $SDKS_DIR/openapi-generator-config.python.yaml
          echo "packageVersion: ${VERSION#v}" >> $SDKS_DIR/openapi-generator-config.python.yaml

      - name: Generate Python Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: python
          config-file: ${{env.SDKS_DIR}}/openapi-generator-config.python.yaml
          openapi-file: ${{env.SPEC_FILE}}

      - name: Move Python SDK
        run: |
          cp -r $PYTHON_GEN_SDK_DIR/* $PYTHON_CLIENT_DIR/
          rm -rf $PYTHON_GEN_SDK_DIR

      - name: Commit and Push SDKs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh auth status
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update SDKs to $VERSION" || (echo "No changes to commit" && exit 1)
          git push origin main