name: Generate OpenAPI Spec

on:
  push:
    tags:
      - 'v*'
env:
  SDKS_DIR: "sdks"
  GO_CLIENT_DIR: "sdks/nexeres-go"
  NODE_CLIENT_DIR: "sdks/nexeres-node"
  SPEC_FILE: "sdks/swagger.yaml"

jobs:
  update-spec-and-sdks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Get Version tags
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Clean up old OpenAPI Spec
        run: rm -rf $SPEC_FILE
      
      - name: Generate OpenAPI Spec
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.4
          swag init -o $SDKS_DIR/temp
          mv $SDKS_DIR/temp/swagger.yaml $SPEC_FILE
          rm -rf $SDKS_DIR/temp

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Bump version in Node SDK
        working-directory: ${{env.NODE_CLIENT_DIR}}
        run: |
          npm --no-git-tag-version version $VERSION

      - name: Push Spec and Node SDK changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update OpenAPI Spec and Node SDK to $VERSION" || echo "No changes to commit"
          git push -u origin main
      
      - name: Publish Node SDK to npm
        working-directory: ${{env.NODE_CLIENT_DIR}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run build
          npm publish